name: foodpanda_ui
description: Complete Foodpanda Clone
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  google_maps_flutter: ^2.6.0

flutter:
  uses-material-design: true
